  # Database connection configuration
  spring:
    datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/employee_management?createDatabaseIfNotExist=true
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASSWORD:1234567890}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

    mail:
      host: smtp.gmail.com
      port: 587
      username: hieu123xx@gmail.com
      password: odqe asxq ysai eecp
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

  payment:
    vnPay:
      url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
      tmnCode: "B392S5MZ"
      secretKey: "GIGCQNW0JPP8IW4OM6CURR1M8R1EAUZ7"
      returnUrl: "http://localhost:8080/api/v1/payment/vnpay-callback"
      version: "2.1.0"
      command: "pay"
      orderType: "other"

  jwt:
    secret: "your1super1long1secret1key1with1641or1more1characters10123456789abc"
    expiration: 36000000
    refresh-secret: "d83sfdsdfsdfwrioewfjjjjewrw3246238948nfdsf889fsd89sdf"
    refresh-expiration: 86400000
  base64:
    key : "q2ert0yu3iopasdf5gvzjl"
  server:
    port: 8081


  upload:
    dir: uploads



